---
- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Install os packages
  apt:
    pkg: "{{ apt_packages }}"
    state: latest

- name: Remove os package
  apt:
    pkg: "{{ remove_apt_packages }}"
    state: absent

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
