---
- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin
    creates=/usr/local/bin/composer.phar
  become: yes

- name: Create composer directory
  file: dest=/home/{{ ansible_env.USER }}/.composer state=directory

- name: Update composer
  shell: composer.phar selfupdate
  become: yes
