---
- name: Update apt
  apt:
    update_cache: yes
  become: yes

- name: Add PHP ppa repository
  apt_repository:
    repo: ppa:ondrej/php
  become: yes

- name: Install core packages
  apt:
    pkg: "{{php_packages}}"
    state: latest
  become: yes

- name: Create PHP log directory
  file:
    dest: /var/log/php
    state: directory
  become: yes

- name: Copy php.ini file
  copy:
    src: 99-php.ini
    dest: /etc/php/{{php_version}}/cli/conf.d/
    mode: 0644
  become: yes
